version: "3"

vars:
  TARGET: ~/.config/nvim

tasks:
  backup:
    silent: true
    cmds: 
      - cmd: rm -rfq ~/.local/share/nvim
        ignore_error: true
      - cmd: mv {{.TARGET}} {{.TARGET}}.{{.TIMESTAMP}}
        ignore_error: true
      - echo "Your config has been backed up at {{.TARGET}}.{{.TIMESTAMP}}"
    vars:
      TIMESTAMP: 
        sh: echo {{now | date "2006-01-02_23:59:59"}}
  checkout:
    silent: true
    cmds: 
      - cmd: git clone git@github.com:sullrich84/nvim.git --depth 1 {{.TARGET}}
  install_or_upgrade:
    internal: true
    cmds:
      - cmd: |
          if brew ls --version "{{.APP}}" >/dev/null; then
            HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade "{{.APP}}"
          else
            HOMEBREW_NO_AUTO_UPDATE=1 brew install "{{.APP}}"
          fi
  dependencies:
    silent: true
    cmds:
      - task: install_or_upgrade
        vars: { APP: typescript-language-server }
      - task: install_or_upgrade 
        vars: { APP: vscode-langservers-extracted }
      - task: install_or_upgrade
        vars: { APP: lazygit }
      - task: install_or_upgrade
        vars: { APP: fzf }
  install:
    silent: true
    cmds:
      - task: backup
      - task: checkout
      - task: dependencies
